spring.application.name=demo2
# ===============================
# 1. C?U HÌNH MYSQL (Bài 4.1 - User)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/demo_week4?useSSL=false&serverTimezone=UTC
# ?i?n user và password MySQL c?a máy b?n (Th??ng m?c ??nh là root)
spring.datasource.username=root
spring.datasource.password=root

# Tính n?ng ma thu?t: T? ??ng t?o b?ng (CREATE TABLE) trong MySQL d?a trên class @Entity
spring.jpa.hibernate.ddl-auto=update
# In câu l?nh SQL ra c?a s? Console ?? d? theo dõi
spring.jpa.show-sql=true

# ===============================
# 2. C?U HÌNH MONGODB (Bài 4.2 - Log)
# ===============================
spring.mongodb.uri=mongodb://localhost:27017/user_logs
# C?u hình k?t n?i Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379